name: Trigger repo1 Workflow

on:
  push:
    branches:
      - main  # or your desired branch

jobs:
  trigger-repo1:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger repo1 workflow
        run: |
          curl -X POST https://api.github.com/repos/RaMayans007/repo1/dispatches \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.REPO1_TOKEN }}" \
            -d '{"event_type":"run-script"}'
