name: trigger_repo_1
on:
  push:
    branches:
      - main

jobs:
  send-webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Send dispatch
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.MY_PAT }}" \
            https://api.github.com/repos/RaMayans007/repo1/actions/workflows/webhook-trigger.yml/dispatches \
            -d '{"ref":"master"}'

      # - name: Send Dispatch Event to Repo1Add commentMore actions
      #   run: |
      #     curl -X POST "https://api.github.com/repos/RaMayans007/repo1/dispatches" \
      #     -H "Authorization: token ${{ secrets.WEBHOOK_PAT }}" \
      #     -H "Accept: application/vnd.github.v3+json" \
      #     -H "Content-Type: application/json" \
      #     -H "X-Hub-Signature-256: sha256=$(echo -n ${{ secrets.WEBHOOK_SECRET }} | openssl dgst -sha256 -hmac ${{ secrets.WEBHOOK_SECRET }} | cut -d " " -f2)" \
      #     -d '{"event_type": "trigger-script"}'
